### ISSUE TITLE
Assembly version of decoder panics on windows

### ISSUE THREAD

**Issue by animesh2049** [dgryski/go-groupvarint#2]
Stack trace
```
unexpected fault address 0xc08c52e000
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xc08c52e000 pc=0xc64e61]

goroutine 1875499 [running]:
runtime.throw(0x11f1aff, 0x5)
        c:/go/src/runtime/panic.go:774 +0x79 fp=0xc00b0e9600 sp=0xc00b0e95d0 pc=0x432bf9
runtime.sigpanic()
        c:/go/src/runtime/signal_windows.go:236 +0x228 fp=0xc00b0e9630 sp=0xc00b0e9600 pc=0x4468a8
github.com/dgraph-io/dgraph/vendor/github.com/dgryski/go-groupvarint.Decode4(0xc00b0e96a8, 0x4, 0x4, 0xc08c52dff0, 0xb, 0x10)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/vendor/github.com/dgryski/go-groupvarint/decode_amd64.s:11 +0x11 fp=0xc00b0e9638 sp=0xc00b0e9630 pc=0xc64e61
github.com/dgraph-io/dgraph/codec.(*Decoder).unpackBlock(0xc020db22d0, 0xc03f00e000, 0x2966278, 0x0)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/codec/codec.go:145 +0x225 fp=0xc00b0e96e0 sp=0xc00b0e9638 pc=0xc65675
github.com/dgraph-io/dgraph/codec.(*Decoder).Seek(0xc020db22d0, 0x0, 0x1, 0x0, 0x0, 0x0)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/codec/codec.go:177 +0x2c9 fp=0xc00b0e9760 sp=0xc00b0e96e0 pc=0xc65b69
github.com/dgraph-io/dgraph/posting.(*pIterator).init(0xc00b0e98c0, 0xc020dd4ae0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/posting/list.go:127 +0x191 fp=0xc00b0e97e0 sp=0xc00b0e9760 pc=0xc77b01
github.com/dgraph-io/dgraph/posting.(*List).iterate(0xc020dd4ae0, 0x360c, 0x0, 0xc00b0e9970, 0xc62571, 0x0)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/posting/list.go:615 +0x118 fp=0xc00b0e9938 sp=0xc00b0e97e0 pc=0xc79d18
github.com/dgraph-io/dgraph/posting.(*List).length(0xc020dd4ae0, 0x360c, 0x0, 0x1)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/posting/list.go:691 +0x98 fp=0xc00b0e9990 sp=0xc00b0e9938 pc=0xc7a4e8
github.com/dgraph-io/dgraph/posting.(*Txn).addMutationHelper(0xc0207eca40, 0x13d1de0, 0xc03d160480, 0xc020dd4ae0, 0x20dc0100, 0xc01c2aab40, 0xc000000000, 0x0, 0x0, 0xc01eb45600, ...)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/posting/index.go:356 +0x51f fp=0xc00b0e9b08 sp=0xc00b0e9990 pc=0xc7338f
github.com/dgraph-io/dgraph/posting.(*List).AddMutationWithIndex(0xc020dd4ae0, 0x13d1de0, 0xc03d160480, 0xc01c2aab40, 0xc0207eca40, 0x0, 0x0)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/posting/index.go:394 +0x124 fp=0xc00b0e9cc8 sp=0xc00b0e9b08 pc=0xc73b24
github.com/dgraph-io/dgraph/worker.runMutation(0x13d1de0, 0xc03d160480, 0xc01c2aab40, 0xc0207eca40, 0x0, 0x0)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/worker/mutation.go:115 +0x38c fp=0xc00b0e9ec0 sp=0xc00b0e9cc8 pc=0xdc6e9c
github.com/dgraph-io/dgraph/worker.(*node).applyMutations.func3(0xc002040000, 0x1f4, 0x400, 0xc85b65, 0xc0102f71c0)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/worker/draft.go:289 +0xb8 fp=0xc00b0e9f70 sp=0xc00b0e9ec0 pc=0xdeb8a8
github.com/dgraph-io/dgraph/worker.(*node).applyMutations.func4(0xc0207e77a0, 0xc01eb45710, 0xc026241200, 0x0, 0x1f4)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/worker/draft.go:318 +0x7e fp=0xc00b0e9fb8 sp=0xc00b0e9f70 pc=0xdebabe
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00b0e9fc0 sp=0xc00b0e9fb8 pc=0x460ca1
created by github.com/dgraph-io/dgraph/worker.(*node).applyMutations
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/worker/draft.go:317 +0x9c7

goroutine 1 [semacquire, 15 minutes]:
sync.runtime_Semacquire(0xc0003fc2d8)
        c:/go/src/runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc0003fc2d0)
        c:/go/src/sync/waitgroup.go:130 +0x6b
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.setupServer()
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:419 +0x82b
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.run()
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:565 +0xd88
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.init.2.func1(0xc0000d6b40, 0xc000720160, 0x0, 0x1)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:87 +0x6d
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute(0xc0000d6b40, 0xc000720140, 0x1, 0x1, 0xc0000d6b40, 0xc000720140)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702 +0x28c
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1c73b00, 0x0, 0x0, 0x0)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783 +0x2d0
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736
github.com/dgraph-io/dgraph/dgraph/cmd.Execute()
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:68 +0x87
main.main()
        C:/Users/ashish/projects/src/github.com/dgraph-io/dgraph/dgraph/main.go:33 +0x9b
```

**Comment by animesh2049** [comment]
Link to original Dgraph Issue: https://github.com/dgraph-io/dgraph/issues/4020
Seems like a golang issue to me. Link to golang issues: https://github.com/golang/go/issues/23279, https://github.com/golang/go/issues/14631

**Comment by dgryski** [comment]
I think this is probably #1 .  Having an actually failing decode input will help here.

**Comment by dgryski** [comment]
This was #1
